sudo: true
language: generic
dist: bionic

jobs:
    include:
        - stage: Check and Build
          env: TARGET=checks.x86_64-linux.build
        - env: TARGET=images.hyperv-image
        - env: TARGET=images.hyperv-dev-image
        - env: TARGET=images.virtualbox-image
        - stage: Release
          if: tag IS present
          env: TARGET=images.all
          deploy:
            provider: releases
            api_key:
                secure: CxAUzq1W9xOc4s5Ca2TovyPoXxXQytkx/++FIx4HCXYvrJVvNZv+w9e4CHLvTMDfUfC0FuFs4EAyy9WARcjELdD1RYkseX6C33jEm5g1lzwq4lFfEUVKoTEOoZWh47ykt1kUjlfK/joHOjnEoZCm5hIyil2JBql94v3AwozJcmg=
            file_glob: true
            file: result/*
            skip_cleanup: true
            on:
                tags: true

install:
    # fix kvm permissions
    - sudo chmod o+rw /dev/kvm

    # install and configure nix
    - curl -L https://nixos.org/nix/install | sh
    - . /home/travis/.nix-profile/etc/profile.d/nix.sh
    - sudo mkdir -p /etc/nix
    - echo "binary-caches = https://cache.nixos.org https://xtruder-public.cachix.org" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= xtruder-public.cachix.org-1:+qG/fM2195QJcE2BXmKC+sS4mX/lQHqwjBH83Rhzl14=" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo "system-features = nixos-test benchmark big-parallel kvm" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf > /dev/null

    # setup caching
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix use xtruder-public

    # install nix with flakes support
    - nix-env -f https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz -iA nixFlakes

before_script:
    - if [ -n "$CACHIX_SIGNING_KEY" ]; then cachix push xtruder-public --watch-store; fi &
    - if [ ! -z "$NIXOS_EXTRA_MODULE" ]; then echo "$NIXOS_EXTRA_MODULE" > extra-module.nix; else echo "{}" > extra-module.nix; fi
    - export NIXOS_EXTRA_MODULE_PATH=$PWD/extra-module.nix

script:
    - nix build --impure .#$TARGET
